# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c1cb423e64ada55b671ecb73d33818ba382e3e1db9567850abddac434fce3ebb2ed5d194d7215102f33b5260e7763e942e8b745ab517f1f72dfed78a575010

test:
  secret_key_base: fdc033d4d4c8983209e3e3ab04c67c43eade4b3a37e1b28af2f3759d138998ee282b93fc51c656b3fe174ab6919375c4c77d90be9b26c83c45280770e472b3bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
